#!/bin/sh
set -e

escape_shell() {
	echo "$@" | sed -e "s#'#'\"'\"'#g"
}

case "$1" in
README)
	TMPFILE="$(mktemp)"
	test -n "$TMPFILE" || exit 1
	trap "cd /; rm '$(escape_shell "$TMPFILE")';" 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
	echo '<html><head><title>dotPageMod: README</title><meta charset="utf-8" /></head><body>' > "${TMPFILE}"
	pandoc --to=html5 README.md >> "${TMPFILE}"
	echo '</body></html>' >> "${TMPFILE}"
	cp "${TMPFILE}" README.html
	;;
app.json)
	ADDON_DIR="$(readlink -f "$(dirname "$0")")"
	sed -e "s|@@ADDON_PATH@@|${ADDON_DIR}|" "${ADDON_DIR}/app/dotpagemod_app.json.in" > "${ADDON_DIR}/app/dotpagemod_app.json"
	;;
*)
	echo >&1 'Command not implemented';;
esac
