#!/bin/sh
set -e

case "$1" in
README)
	TMPFILE="$(mktemp)"
	test -n "$TMPFILE" || exit 1
	trap 'cd /; rm "${TMPFILE}";' 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
	cat <<EOF > "${TMPFILE}"
<!DOCTYPE html>
<html>
	<head>
		<title>dotPageMod: README</title>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link id="favicon" rel="icon" type="image/png" href="/icon.png" />
	</head><body>
EOF
	pandoc --to=html5 README.md >> "${TMPFILE}"
	echo '</body></html>' >> "${TMPFILE}"
	cp "${TMPFILE}" README.html
	;;
app.json)
	ADDON_DIR="$(readlink -f "$(dirname "$0")")"
	sed -e "s|@@ADDON_PATH@@|${ADDON_DIR}|" "${ADDON_DIR}/app/dotpagemod_app.json.in" > "${ADDON_DIR}/app/dotpagemod_app.json"
	;;
*)
	echo >&1 'Command not implemented';;
esac
